# Specify service name.
service : backend

# Specify runtime environment.
runtime: python

# Use ubuntu22 with latest python version.
runtime_config:
    operating_system: "ubuntu22"

# Specify flexible environment to enable websockets.
env: flex

# Specify command to start the application.
entrypoint: gunicorn -k uvicorn.workers.UvicornWorker main:app

# Specify resource to be used for instances.
resources:
  cpu: 1
  memory_gb: 4.4
  disk_size_gb: 10

# Specify autoscaling of instances.
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

# Set environment variables.
env_variables:
  SECRET_KEY: $SECRET_KEY

  JWT_ACCESS_SECRET_KEY: $JWT_ACCESS_SECRET_KEY
  JWT_REFRESH_SECRET_KEY: $JWT_REFRESH_SECRET_KEY

  GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
  GOOGLE_REDIRECT_URI: $GOOGLE_REDIRECT_URI

  GOOGLE_CLOUD_STORAGE_URI: $GOOGLE_CLOUD_STORAGE_URI
  GOOGLE_BUCKET_NAME: $GOOGLE_BUCKET_NAME
  GOOGLE_BUCKET_LEGAL_DOCUMENT_FOLDER_NAME: $GOOGLE_BUCKET_LEGAL_DOCUMENT_FOLDER_NAME

  FRONTEND_URL: $FRONTEND_URL
  RAG_URL: $RAG_URL

  DATABASE_USER: $DATABASE_USER
  DATABASE_PASS: $DATABASE_PASS
  DATABASE_HOST: $DATABASE_HOST
  DATABASE_PORT: $DATABASE_PORT
  DATABASE_NAME: $DATABASE_NAME

  ELASTICSEARCH_URL: $ELASTICSEARCH_URL
  ELASTICSEARCH_API_KEY: $ELASTICSEARCH_API_KEY
  ELASTICSEARCH_USERNAME: $ELASTICSEARCH_USERNAME
  ELASTICSEARCH_PASSWORD: $ELASTICSEARCH_PASSWORD
  ELASTICSEARCH_LEGAL_DOCUMENT_INDEX: $ELASTICSEARCH_LEGAL_DOCUMENT_INDEX

  RABBITMQ_HOST: $RABBITMQ_HOST
  RABBITMQ_PORT: $RABBITMQ_PORT
  RABBITMQ_USER: $RABBITMQ_USER
  RABBITMQ_PASS: $RABBITMQ_PASS

  RABBITMQ_QUEUE: $RABBITMQ_QUEUE
  RABBITMQ_EXCHANGE: $RABBITMQ_EXCHANGE
  RABBITMQ_ROUTING_KEY: $RABBITMQ_ROUTING_KEY
