# Specify service name.
service : backend

# Specify runtime environment.
runtime: python

# Use ubuntu22 with latest python version.
runtime_config:
    operating_system: "ubuntu22"

# Specify flexible environment to enable websockets.
env: flex

# Specify command to start the application.
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

# Specify autoscaling of instances.
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

# Set environment variables.
env_variables:
  DB_USER: $DB_USER
  DB_PASS: $DB_PASS
  DB_PORT: $DB_PORT
  DB_NAME: $DB_NAME
  DB_HOST: $DB_HOST

  SECRET_KEY: $SECRET_KEY

  JWT_ACCESS_SECRET_KEY: $JWT_ACCESS_SECRET_KEY
  JWT_REFRESH_SECRET_KEY: $JWT_REFRESH_SECRET_KEY

  GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
  GOOGLE_REDIRECT_URI: $GOOGLE_REDIRECT_URI

  FRONTEND_URL: $FRONTEND_URL
  RAG_URL: $RAG_URL
